lec11 english version
moonbitlang/moonbit-course pull request #18
Opened 2024-05-20 02:41 UTC by yqyq-w

- [ ] course11/course_en.md: Slides
- [ ]course11/lecture_en.md: Notes
- [ ]course11 linting, and add linted code & figures into lecture_en [In progress]

2024-05-23 06:12 UTC, peter-jerry-ye requested changes

2024-05-23 06:12 UTC, peter-jerry-ye commented on course11/course_en.md
> +  fn init {
Change to test:
```
fn test {
    inspect(pchar(fn{ ch => ch == 'a' }).parse("asdf"), contet="")?
    inspect(pchar(fn{ 
      'a' => true
       _  => false
    }).parse("sdf"), content="None")?
}
```

2024-05-23 06:12 UTC, peter-jerry-ye commented on course11/lecture_en.md
> +
Parsing is missing here...

2024-05-23 06:12 UTC, peter-jerry-ye commented on course11/lecture_en.md
> +```moonbit expr
Why is it here? We haven't introduced `Lexer` nor `pchar` yet.

2024-05-23 06:12 UTC, peter-jerry-ye commented on course11/lecture_en.md
> +We then proceed to build a combinable parser. The parser is a function that takes a string as input and outputs a nullable `Option`. An empty value indicates the pattern matching failed, and a non-em
`Option[T]` itself stands for a nullable value

2024-05-23 06:12 UTC, peter-jerry-ye commented on course11/lecture_en.md
> +      Some((input[0], input.to_bytes().sub_string(2, input.length() * 2 - 2)))
```suggestion
      Some((input[0], input.substring(start=1)))
```
Please kindly check the correctness, and update the source code as well

2024-05-23 06:12 UTC, peter-jerry-ye commented on course11/lecture_en.md
> +fn init {
As mentioned above, please use a test block (and maybe leave it with `no-check`)

2024-05-23 06:12 UTC, peter-jerry-ye commented on course11/lecture_en.md
> +fn reverse_list[X](list : List[X]) -> List[X] {
This function is no longer needed

2024-05-23 06:12 UTC, peter-jerry-ye commented on course11/lecture_en.md
> +    let mut rest = input
```suggestion
    loop input, List::Nil {
        rest, cumul => match self.parse(rest) {
          None => Some((cumul.reverse(), rest))
          Some((value, rest)) => continue rest, Cons(value, cumul)
        }
      }
```

Please check the correctness

2024-05-23 06:12 UTC, peter-jerry-ye commented on course11/lecture_en.md
> +fn fold_left_list[A, B](list : List[A], f : (B, A) -> B, b : B) -> B {
This function is no longer needed

2024-05-23 06:12 UTC, peter-jerry-ye commented on course11/lecture_en.md
> +    fn { (i, ls) => fold_left_list(ls, fn { i, j => i * 10 + j }, i) },
```suggestion
    fn { (i, ls) => ls.fold_left(fn { i, j => i * 10 + j }, init=i) },
```

Please check the correctness

2024-05-23 06:12 UTC, peter-jerry-ye commented on course11/lecture_en.md
> +fn init {
Please change to `test`

2024-05-23 06:12 UTC, peter-jerry-ye commented on course11/lecture_en.md
> +
There should be three versions of grammar. One of them is missing.

2024-05-23 06:12 UTC, peter-jerry-ye commented on course11/lecture_en.md
> +debug((parse_string_tagless_final("1 + 1 * (307 + 7) + 5 - (3 - 2)")
Please use the test syntax here

2024-05-23 16:42 UTC, yqyq-w commented on course11/course_en.md
> +  fn init {
the fn test intruduces the errors, need some help to fix it:
- 101:3-101:4 [E3004] Missing parameters list. Add `()` if function `?fun_binder` has 0 parameter.
- 101:3-101:4 [E4076] Missing type annotation for the return value.
- 101:3-101:4 [E3002] Parse error,unexpected token `test`, you may expect `identifier` or identifier or package name
- 105:55-105:61 [E4085] This constructor has no parameter with label ~contet.
- 101:4-110:2 [E1019] Error (warning): Toplevel declaration is not left aligned.error: failed at build test stage

2024-05-23 16:52 UTC, yqyq-w commented on course11/lecture_en.md
> +fn reverse_list[X](list : List[X]) -> List[X] {
okk, was having it to pass the linter for funtions that uses it, can I `no-check` the functions producing errors if no explicitly defining it (they pass the linter with `reverse_list` defined so it should be good)?

2024-05-23 16:55 UTC, yqyq-w commented on course11/lecture_en.md
> +    let mut rest = input
should I update the `mbt` file as well?

2024-05-23 17:44 UTC, yqyq-w commented
did modify this part of the code but it fails linter now?

2024-05-24 02:58 UTC, peter-jerry-ye commented on course11/course_en.md
> +  fn init {
Sorry, my bad, it should be `test {  xxx }`. The `content=` is the new grammar.

For reference: <https://try.moonbitlang.cn/#f147b954>

2024-05-24 02:58 UTC, peter-jerry-ye commented on course11/lecture_en.md
> +    let mut rest = input
Yes, please

2024-05-27 03:48 UTC, peter-jerry-ye approved these changes

2024-05-27 03:48 UTC, merged